application: ic-stilwiese
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static
  mime_type: "text/css"

- url: /images
  static_dir: images
  mime_type: "image/jpg"

- url: /.*
  script: main.app

libraries:
- name: django
  version: "latest"
