application: ic-stilwiese
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static/admin/css
  static_dir: sitestatic/admin/css
  mime_type: text/css

- url: /static/admin/js
  static_dir: sitestatic/admin/js
  mime_type: text/javascript

- url: /static/foundation/css
  static_dir: sitestatic/foundation/css
  mime_type: text/css

- url: /static/foundation/ja
  static_dir: sitestatic/foundation/ja
  mime_type: text/javascript

- url: /static/stilwiese/css
  static_dir: sitestatic/stilwiese/css
  mime_type: text/css

- url: /static
  static_dir: sitestatic

- url: /images
  static_dir: images

- url: /.*
  script: main.app

libraries:
- name: django
  version: "latest"
