application: ic-stilwiese
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /files
  static_dir: files

- url: /.*
  script: main.app

libraries:
- name: django
  version: "latest"
